language: node_js

cache:
  directories:
    - '$HOME/.npm'

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install: npm ci

script:
  - npm run lint
  - npm run test
  - npm run dist
  - npm run site

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key:
      secure: HzU0LCvMf9JJIglK7b6JBlGlNUPohy1dsrLOpruITgQeqjnjXti03UUer0wKtBFZXg/ZoWkwGZwQ3dqgf8D3Ilb87XjVWWARSszbQsVZ/BiXN86DkZOjCuowa6usThL/NcnU1lzLh+TZx6EoYfNCtZygGCJCJNVsLVIfS5X7zuJeLC3O7AhB9a2maHS6cztFBjAd5gYkw0F/sHLbKBoy3O4uNJkX4aI+0WQ5aKQt3GGEELkcDlBTmmt5KCb5diSNiwwXlvqS+XXcYAIwk6ynwgIZcvKGyFEDujGIwajykbg7C5ZxKDhoEAgtU9CvpRbFWuyZfbRvkuGEStGG0c+ExH8lLQ2OtJNJEafolLd90sXXR3tFuxH33RZSGvRNp2fJRYej0OlOJYv+K/q9BdIQZGTChleel+Ml9cFJl900ClhNGAmWVz7pGHQNJBID3ZJZC8PeqEd3ZB5gwZoSVERKITOTipD19TraEI6za9nn093CLhivN0mbZoqRnJE6t/023yBNgInXoeCVsciaM+AMlL6mqOeX4FKd8+UZwcOk0iPKSiTgQ0HuMMpFbX9Ht2yajHHkPr7m325/O7LerJ1U5xrdxBL1RBr8VJ24tffquMyf3/4WVo7Mb/YuooryolDwjM7TS3cfynLOD935q35Kw90UyZ0QoS9N/6AtUHndYq8=
    skip_cleanup: true
    on:
      tags: true

  - provider: firebase
    token:
      secure: gm6RdjfiYGq0QpXh/3Fz8zD1utc275rz54OeFipBXBbPJIXfehurjHqbHiiAAwIWy7v5jcPOwrNK2QtaWU+nS71SwlyAUvQhX2hZbmj86eR7/Ri7TB2wueO41DG/++Q615x/13Zaudg0oLUYBpCVeDFqBGi0mbjJzlMK6dZwtZI4BniucbNQdag8PN4Wjqd2o07OdyJPS+2FP3FgFG6eJ4IJboWKhPjukyQ+NmUJcXb5vwWOUoOCysdry1pnilR8u9UHr0OQp0zqavf/vsArIGYrwh+nwKv0iMMvbtIV4AzYxUX3QTnocBZN7DqiWx+vSbkpTPjiV+b6bTzPH8v9zhn0NTXPxwibEviiaDWapTR+XPJ71fplHws29ld7Y8bGwLUTh9A3OfIzds8QSDJhHGmKzJS5p9c+L8hyFCsROV63ACbYbBudOpZmt/LSwmirY/eidX19o9oEvcJGB7O3dX541DnLvYcrvPasmbdxPu6bINymiNAtHsO35SMMNIlGTAoGPvAPsFZihKpZWm69lYsdHQEPaxW8pQzqWtEQWAm2Tm8naGStw9C1rA4eXcZyD+o1yFISPO0s2tqP2MWKGNId1gUmT6TbrjbuYSqhpZN7OEETh+Lxr/gOiW8dugSqjxBf+HlL0maU7fVCAsm6eGRk/EnAclUnpOLIoYSf/LA=
    skip_cleanup: true
    on:
      branch: master
