language: node_js
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
before_install: npm install -g npm@5.7.1
install: npm ci
script:
  - npm run lint
  - npm run test
  - npm run dist
  - npm run site
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: site
    skip_cleanup: true
    on:
      branch: master
